// src/views/guide.vue
<template>
    <div>
        <!-- <img :src="one" alt=""> -->



        <mt-swipe :auto="4000" class="guide" :continuous="false" :show-indicators="false">
            <mt-swipe-item v-for="(img,i) in imgs" :key="i">
                <img :src="img" alt=""  @click="gotoHome(i)">
            </mt-swipe-item>
        </mt-swipe>

    </div>
</template>



<script>
    export default {
        name: "guide",
        data() {
            return {
                one: require("@/assets/images/slide1.png"),

                imgs: [
                    require("@/assets/images/slide1.png"),
                    require("@/assets/images/slide2.png"),
                    require("@/assets/images/slide3.png"),
                    require("@/assets/images/slide4.png"),
                ],
            }
        },
        methods: {
            gotoHome(id){
                if(id==this.imgs.length-1){
                    this.$router.push({name:'home'})
                }
            }
        },
        mounted(){
            if(localStorage.num){
                localStorage.num++;
                if(localStorage.num>4){
                    this.$router.push({name:'home'})
                }
            }else{
                localStorage.num=1
            }
        }

    }


</script>
<style lang="css" scoped>
    img {
        width: 100%;
        /* height: 100%; */
    }
</style>

// react-music/src/scripts/views/guide/index.js



import React, { Component } from 'react';
import { Carousel, WingBlank } from 'antd-mobile';
import { history } from "&";

import { connect } from "react-redux";


export class Guide extends Component {
    state = {
        data: [
            require("@/assets/images/pic1.jpg"),
            require("@/assets/images/pic2.jpg"),
            require("@/assets/images/pic3.jpg"),
            require("@/assets/images/pic4.jpg")
        ]
    }
    componentWillMount() {
        if (localStorage.num) {
            localStorage.num++
            if (localStorage.num > 5) {
                history.push('/app/my')
            }
        } else {
            localStorage.num = 1
        }
    }
    go = (i) => {

        if (i == this.state.data.length - 1) {
            setTimeout(() => {

                history.push('/app/my')
            }, 600)
        }
    }

    render() {
        const {
            data
        } = this.state
        return (
            <div>
                <Carousel
                    autoplay={false}
                
                    dots={false}
                    beforeChange={(from, to) => this.go(to)}
                >
                    {data.map((m, i) => (
                        <img
                            key={i}
                            src={m}
                            alt=""
                            style={{ width: '100%', height: '100%', verticalAlign: 'top' }}
                        />
                    ))}
                </Carousel>
            </div>
        )
    }
}
